# Generated by Django 5.2.6 on 2025-09-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='distance_miles',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='duration_hours',
        ),
    ]
