# Generated by Django 5.2.6 on 2025-09-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
